const reportsActionTypes = {
  FETCH_USER_START: "FETCH_USER_START",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAIL: "FETCH_USER_FAIL",

  FETCH_PROJECTS_START: "FETCH_PROJECTS_START",
  FETCH_PROJECTS_SUCCESS: "FETCH_PROJECTS_SUCCESS",
  FETCH_PROJECTS_FAIL: "FETCH_PROJECTS_FAIL",

  FETCH_GATEWAYS_START: "FETCH_GATEWAYS_START",
  FETCH_GATEWAYS_SUCCESS: "FETCH_GATEWAYS_SUCCESS",
  FETCH_GATEWAYS_FAIL: "FETCH_GATEWAYS_FAIL",

  FETCH_REPORTS_START: "FETCH_REPORTS_START",
  FETCH_REPORTS_SUCCESS: "FETCH_REPORTS_SUCCESS",
  FETCH_REPORTS_FAIL: "FETCH_REPORTS_FAIL",



  HANDLE_SET_PROJECT_STATUS: "HANDLE_SET_PROJECT_STATE",
  HANDLE_SET_GATEWAY_STATE: "HANDLE_SET_GATEWAY_STATE"
};

export default reportsActionTypes;
